name: Documentation
# This workflow clones the tendermint/tendermint repository, builds its static
# documentation, and publishes the results to GitHub Pages.
# It runs on every push to the main branch, and every fifteen minutes.
#
# Note that this workflow does not respond to pushes on tendermint/tendermint.
on:
  workflow_dispatch:  # allow manual updates
  push:
    branches:
      - main
  schedule:
    - cron: '1 */2 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: tendermintdev/docker-website-deployment
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: "tendermint/tendermint"

      - name: Install and Build ğŸ”§
        run: |
          apk add rsync
          make build-docs

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/output
          single-commit: true
